2020/03/07 07:37:35 [emerg] 1#1: "log_format" directive is not allowed here in /etc/nginx/conf.d/default.conf:7
2020/03/07 07:45:32 [emerg] 1#1: "log_format" directive is not allowed here in /etc/nginx/conf.d/default.conf:7
2020/03/07 07:48:28 [emerg] 1#1: "log_format" directive is not allowed here in /etc/nginx/conf.d/default.conf:7
2020/03/07 08:27:57 [emerg] 1#1: "http" directive is not allowed here in /etc/nginx/conf.d/default.conf:1
2020/03/07 08:35:01 [emerg] 1#1: host not found in upstream "php_fpm" in /etc/nginx/conf.d/default.conf:18
2020/03/07 08:38:02 [emerg] 1#1: open() "/etc/nginx/logs/access.log" failed (2: No such file or directory)
2020/03/07 12:19:41 [error] 15#15: *2 "/var/www/laravel/public/index.php" is not found (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:19:41 [error] 15#15: *2 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:19:42 [error] 15#15: *2 open() "/var/www/laravel/public/favicon.ico" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET /favicon.ico HTTP/1.1", host: "localhost:180", referrer: "http://localhost:180/"
2020/03/07 12:19:42 [error] 15#15: *2 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET /favicon.ico HTTP/1.1", host: "localhost:180", referrer: "http://localhost:180/"
2020/03/07 12:29:53 [error] 15#15: *6 "/var/www/laravel/public/index.php" is not found (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:29:53 [error] 15#15: *6 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:29:55 [error] 15#15: *6 "/var/www/laravel/public/index.php" is not found (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:29:55 [error] 15#15: *6 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:29:56 [error] 15#15: *6 "/var/www/laravel/public/index.php" is not found (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:29:56 [error] 15#15: *6 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:29:57 [error] 15#15: *6 "/var/www/laravel/public/index.php" is not found (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:29:57 [error] 15#15: *6 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:29:57 [error] 15#15: *6 "/var/www/laravel/public/index.php" is not found (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:29:57 [error] 15#15: *6 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:30:32 [error] 15#15: *6 "/var/www/laravel/public/index.php" is not found (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:30:32 [error] 15#15: *6 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:30:33 [error] 15#15: *6 open() "/var/www/laravel/public/favicon.ico" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET /favicon.ico HTTP/1.1", host: "localhost:180", referrer: "http://localhost:180/"
2020/03/07 12:30:33 [error] 15#15: *6 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET /favicon.ico HTTP/1.1", host: "localhost:180", referrer: "http://localhost:180/"
2020/03/07 12:31:30 [error] 15#15: *6 "/var/www/laravel/public/index.php" is not found (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:31:30 [error] 15#15: *6 open() "/var/www/laravel/public/404.html" failed (2: No such file or directory), client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 12:32:48 [notice] 22#22: signal process started
2020/03/07 12:32:53 [error] 23#23: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://172.25.0.3:9000", host: "localhost:180"
2020/03/07 12:33:40 [error] 23#23: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://172.25.0.3:9000", host: "localhost:180"
2020/03/07 16:20:42 [error] 13#13: *2 "/var/www/laravel/laravel_portfolio/public/index.php" is not found (2: No such file or directory), client: 192.168.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 16:20:42 [error] 13#13: *2 open() "/var/www/laravel/laravel_portfolio/public/404.html" failed (2: No such file or directory), client: 192.168.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 16:21:49 [error] 13#13: *3 "/var/www/laravel/laravel_portfolio/public/index.php" is not found (2: No such file or directory), client: 192.168.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 16:21:49 [error] 13#13: *3 open() "/var/www/laravel/laravel_portfolio/public/404.html" failed (2: No such file or directory), client: 192.168.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 16:22:02 [notice] 14#14: signal process started
2020/03/07 16:22:06 [error] 13#13: *4 "/var/www/laravel/laravel_portfolio/public/index.php" is not found (2: No such file or directory), client: 192.168.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 16:22:06 [error] 13#13: *4 open() "/var/www/laravel/laravel_portfolio/public/404.html" failed (2: No such file or directory), client: 192.168.0.1, server: laravelapp, request: "GET / HTTP/1.1", host: "localhost:180"
2020/03/07 16:22:08 [error] 15#15: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.0.3:9000", host: "localhost:180"
2020/03/07 16:27:40 [error] 15#15: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost:180"
2020/03/07 16:27:42 [error] 15#15: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost:180"
2020/03/07 16:27:43 [error] 15#15: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost:180"
2020/03/07 16:27:44 [error] 15#15: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost:180"
2020/03/07 16:29:38 [notice] 17#17: signal process started
2020/03/07 16:29:51 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost:180"
2020/03/07 16:29:54 [error] 15#15: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.16.3:9000", host: "localhost:180"
2020/03/07 16:33:44 [notice] 19#19: signal process started
2020/03/07 16:33:49 [error] 20#20: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.3:9000", host: "localhost:180"
2020/03/07 17:51:40 [error] 15#15: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/07 17:51:42 [error] 15#15: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/07 17:52:55 [notice] 17#17: signal process started
2020/03/07 17:53:02 [error] 18#18: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/07 17:53:06 [error] 18#18: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/07 17:53:11 [error] 18#18: *5 open() "/var/www/laravel_portfolio/public/index" failed (2: No such file or directory), client: 192.168.32.1, server: laravelapp, request: "GET /index HTTP/1.1", host: "localhost:180"
2020/03/07 17:53:11 [error] 18#18: *5 open() "/var/www/laravel_portfolio/public/404.html" failed (2: No such file or directory), client: 192.168.32.1, server: laravelapp, request: "GET /index HTTP/1.1", host: "localhost:180"
2020/03/07 17:53:18 [error] 18#18: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/07 18:00:37 [error] 18#18: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/07 18:00:39 [error] 18#18: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", c host: "localhost:180"
2020/03/07 18:10:58 [notice] 28#28: signal process started
2020/03/07 18:10:58 [emerg] 14#14: bind() to 127.0.0.1:80 failed (98: Address in use)
2020/03/07 18:10:58 [emerg] 14#14: bind() to 127.0.0.1:80 failed (98: Address in use)
2020/03/07 18:10:58 [emerg] 14#14: bind() to 127.0.0.1:80 failed (98: Address in use)
2020/03/07 18:10:58 [emerg] 14#14: bind() to 127.0.0.1:80 failed (98: Address in use)
2020/03/07 18:10:58 [emerg] 14#14: bind() to 127.0.0.1:80 failed (98: Address in use)
2020/03/07 18:10:58 [emerg] 14#14: still could not bind()
2020/03/07 18:11:03 [error] 18#18: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/07 18:11:05 [error] 18#18: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/07 18:11:06 [error] 18#18: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/07 18:15:42 [notice] 29#29: signal process started
2020/03/07 18:15:45 [error] 30#30: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:19000", host: "localhost:180"
2020/03/07 18:15:49 [error] 30#30: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:19000", host: "localhost:180"
2020/03/07 18:17:01 [error] 30#30: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:19000", host: "localhost:180"
2020/03/07 18:19:28 [error] 30#30: *34 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:19000", host: "localhost:180"
2020/03/07 18:22:56 [error] 30#30: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: laravelapp, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:19000", host: "localhost:180"
2020/03/08 03:32:19 [emerg] 14#14: "user" directive is not allowed here in /etc/nginx/conf.d/default.conf:3
2020/03/08 03:32:50 [emerg] 15#15: "user" directive is not allowed here in /etc/nginx/conf.d/default.conf:2
2020/03/08 03:33:14 [error] 18#18: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:19000", host: "localhost:180"
2020/03/08 03:35:52 [notice] 20#20: signal process started
2020/03/08 03:36:01 [error] 21#21: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 03:41:24 [error] 21#21: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 03:51:00 [error] 21#21: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 03:51:11 [error] 21#21: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 03:52:36 [error] 21#21: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 03:52:39 [error] 21#21: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 03:52:39 [error] 21#21: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 03:52:55 [notice] 22#22: signal process started
2020/03/08 03:52:58 [error] 21#21: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 03:53:00 [error] 23#23: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 03:53:01 [error] 23#23: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:180"
2020/03/08 04:09:01 [notice] 26#26: signal process started
2020/03/08 04:09:06 [error] 27#27: *27 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.48.3:9000", host: "localhost:180"
2020/03/08 04:09:34 [error] 27#27: *27 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.48.3:9000", host: "localhost:180"
2020/03/08 04:10:55 [notice] 28#28: signal process started
2020/03/08 04:11:01 [error] 27#27: *31 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.48.3:9000", host: "localhost:180"
2020/03/08 04:11:03 [error] 29#29: *32 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.48.3:9000", host: "localhost:180"
2020/03/08 04:15:02 [error] 29#29: *36 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.48.3:9000", host: "localhost:180"
2020/03/08 04:15:14 [notice] 32#32: signal process started
2020/03/08 04:15:17 [error] 29#29: *37 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.48.3:9000", host: "localhost:180"
2020/03/08 04:19:24 [notice] 34#34: signal process started
2020/03/08 07:25:38 [error] 15#15: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:25:51 [error] 15#15: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:34:00 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:34:02 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:34:04 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:34:07 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:34:16 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:34:24 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:34:56 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:34:59 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:35:01 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:36:05 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:36:07 [error] 15#15: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:39:41 [notice] 29#29: signal process started
2020/03/08 07:39:53 [error] 30#30: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:42:21 [error] 30#30: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:42:23 [error] 30#30: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:42:25 [error] 30#30: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:43:25 [error] 30#30: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "127.0.0.1:58710"
2020/03/08 07:46:32 [error] 30#30: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.80.3:58720", host: "localhost:58710"
2020/03/08 07:50:26 [error] 15#15: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:58720", host: "localhost:58710"
2020/03/08 07:50:56 [error] 15#15: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:58720", host: "localhost:58710"
2020/03/08 08:04:41 [error] 15#15: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:58720", host: "localhost:58710"
2020/03/08 08:05:18 [error] 15#15: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:58720", host: "localhost:58710"
2020/03/08 08:10:40 [error] 14#14: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:58720", host: "localhost:58710"
2020/03/08 08:13:13 [notice] 21#21: signal process started
2020/03/08 08:13:16 [error] 14#14: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.3:58720", host: "localhost:58710"
2020/03/08 08:17:43 [error] 13#13: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.3:58720", host: "localhost:58710"
2020/03/08 08:18:56 [error] 13#13: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.3:58720", host: "localhost:58710"
2020/03/08 08:18:58 [error] 13#13: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.3:58720", host: "localhost:58710"
2020/03/08 08:18:59 [error] 13#13: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.3:58720", host: "localhost:58710"
2020/03/08 08:21:26 [error] 13#13: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.3:58720", host: "localhost:58710"
2020/03/09 15:13:30 [error] 13#13: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.144.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.144.3:58720", host: "localhost:58710"
2020/03/09 15:39:37 [error] 15#15: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.160.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.160.3:9000", host: "localhost:58710"
2020/03/09 16:12:33 [error] 16#16: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.192.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.192.3:9000", host: "localhost:58710"
2020/03/14 13:26:45 [emerg] 21#21: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:26:45 [emerg] 21#21: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:26:45 [emerg] 21#21: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:26:45 [emerg] 21#21: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:26:45 [emerg] 21#21: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:26:45 [emerg] 21#21: still could not bind()
2020/03/14 13:27:21 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:27:21 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:27:21 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:27:21 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:27:21 [emerg] 23#23: bind() to 0.0.0.0:80 failed (98: Address in use)
2020/03/14 13:27:21 [emerg] 23#23: still could not bind()
2020/03/14 13:28:45 [error] 15#15: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.3:9000", host: "localhost:58710"
2020/03/14 13:28:57 [notice] 24#24: signal process started
2020/03/14 13:29:08 [error] 27#27: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.3:9000", host: "localhost:58710"
2020/03/19 17:04:10 [error] 16#16: *1 directory index of "/var/www/vue_portfolio/" is forbidden, client: 192.168.32.1, server: vue_front, request: "GET / HTTP/1.1", host: "localhost:58730"
2020/03/19 17:04:11 [error] 16#16: *1 open() "/var/www/vue_portfolio/favicon.ico" failed (2: No such file or directory), client: 192.168.32.1, server: vue_front, request: "GET /favicon.ico HTTP/1.1", host: "localhost:58730", referrer: "http://localhost:58730/"
2020/03/19 17:04:11 [error] 16#16: *1 open() "/var/www/vue_portfolio/404.html" failed (2: No such file or directory), client: 192.168.32.1, server: vue_front, request: "GET /favicon.ico HTTP/1.1", host: "localhost:58730", referrer: "http://localhost:58730/"
2020/03/19 17:04:22 [error] 16#16: *1 directory index of "/var/www/vue_portfolio/" is forbidden, client: 192.168.32.1, server: vue_front, request: "GET / HTTP/1.1", host: "localhost:58730"
2020/03/19 17:05:38 [notice] 22#22: signal process started
2020/03/19 17:07:35 [error] 28#28: *1 "/var/www/vue_portfolio/index.html/index.html" is not found (2: No such file or directory), client: 192.168.32.1, server: vue_front, request: "GET / HTTP/1.1", host: "localhost:58730"
2020/03/19 17:07:35 [error] 28#28: *1 open() "/var/www/vue_portfolio/index.html/404.html" failed (2: No such file or directory), client: 192.168.32.1, server: vue_front, request: "GET / HTTP/1.1", host: "localhost:58730"
2020/03/19 17:08:45 [notice] 33#33: signal process started
